USE QLPHONGTRO

CREATE TABLE tbKhachHang (
  IDKhachHang INT NOT NULL IDENTITY(1,1),
  Ho VARCHAR(50) NOT NULL,
  Ten VARCHAR(50) NOT NULL,
  CMND VARCHAR(12) NOT NULL,
  SoDienThoai VARCHAR(11) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  DiaChi VARCHAR(255) NOT NULL,
  PRIMARY KEY (IDHoaDon)
);

CREATE TABLE tbHopDong (
  IDHopDong INT NOT NULL IDENTITY(1,1),
  IDKhachHang INT NOT NULL,
  NgayLamHopDong DATE NOT NULL,
  NgayKetThucHopDong DATE NOT NULL,
  SoLuongNgayThue INT NOT NULL,
  GiaPhong INT NOT NULL,
  TongTien INT NOT NULL,
  DaThanhToan INT NOT NULL,
  PRIMARY KEY (IDHopDong),
  FOREIGN KEY (IDHoaDon) REFERENCES tbKhachHang (IDHoaDon)
);

CREATE TABLE tbLoaiPhong (
  TentosPhong INT NOT NULL IDENTITY(1,1),
  TenLoaiPhong VARCHAR(50) NOT NULL,
  GiaPhong INT NOT NULL,
  PRIMARY KEY (TentosPhong)
);

CREATE TABLE tbDichVu (
  IDDV INT NOT NULL IDENTITY(1,1),
  TenDV VARCHAR(50) NOT NULL,
  DonGia INT NOT NULL,
  PRIMARY KEY (IDDV)
);

CREATE TABLE tbHopDongDV (
  IDHopDong INT NOT NULL,
  IDDV INT NOT NULL,
  SoLuong INT NOT NULL,
  ThanhTien INT NOT NULL,
  PRIMARY KEY (IDHopDong, IDDV),
  FOREIGN KEY (IDHopDong) REFERENCES tbHopDong (IDHopDong),
  FOREIGN KEY (IDDV) REFERENCES tbDichVu (IDDV)
);

CREATE TABLE tbPhong (
  SoPhong INT NOT NULL IDENTITY(1,1),
  TentosPhong INT NOT NULL,
  TinhTrang INT NOT NULL,
  PRIMARY KEY (SoPhong),
  FOREIGN KEY (TentosPhong) REFERENCES tbLoaiPhong (TentosPhong)
);
